In [1]:
import numpy as np
A=np.mat("1,2,3;4,5,6;7,8,9")
print(A,"\n")
inverse=np.linalg.pinv(A)
print(inverse)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  1.38777878e-16  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]


In [2]:
import numpy as np
import time
SIZE=100000
a=range(SIZE)
b=range(SIZE)
ar=np.arange(SIZE)
br=np.arange(SIZE)
# Normal List
start=time.time()
result=[(x+y) for x,y in zip(a,b)]
print("Time took by pyhton list : ",(time.time()-start)*1000)
#print(result)

# Numpy array
start=time.time()
result=ar+br
print("Time took by numpy array : ",(time.time()-start)*1000)
#print(result)

Time took by pyhton list :  29.55174446105957
Time took by numpy array :  4.825592041015625


In [3]:
import numpy as np
#fing size of array through numpy
array=np.arange(20)
print(array.size)
print(array.itemsize*array.size)
#finding Length or size of list
a=[1,2,2,3,4,5]
print(len(a))

20
80
6
