In [45]:
import random
import numpy as np
import matplotlib.pyplot as plt

In [96]:
# Function for sigmoid
def sigmoid(a):
    return ((1.0)/(1 + np.exp(-a)))

# Function for generating data
def gen_data(rows, variance):
    X = np.zeros(shape = (rows, 2))
    y = np.zeros(shape = rows)
    
    for i in range(0, rows):
        X[i][0] = 1
        X[i][1] = random.uniform(10, 30)
#         X[i][2] = i+1 # use for multi variable if u want n then change X shape or column to n and also 
        #and add values to those column here,...........PEACE OUT
        y[i] = random.randint(0, 1)
    
    return X, y

# Gradient descent main Function
def grad_desc(X, y, alpha, num_iter, theta, m):
    
    X_trans = X.T
    
    for i in range(0, num_iter):
        prediction = sigmoid(np.dot(X, theta))
        error = sigmoid(prediction) - y
        cost = (np.dot(-y, np.log(prediction)) - np.dot((1 - y), np.log(1 - prediction))) / m # Cost Function  it
        print("Iteration : %d | Cost : %f" %(i, cost))
        # Calculation for gradient descent starts now
        gradient = np.dot(X_trans, error) / m
        theta = theta - alpha * gradient
    
    return theta

X,y = gen_data(100, 10)
m, n = np.shape(X)
theta = np.ones(n)
num_iter = 100 # number of iteration u want to perform feel free to change it as much as u want
alpha = 0.0005 #Alpha or so called learning factor
theta = grad_desc(X, y, alpha, num_iter, theta, m)
print("\nValues of THETA after "+str(num_iter)+" Iteration is = \n")
print(theta)
# print(X)

Iteration : 0 | Cost : 9.995402
Iteration : 1 | Cost : 9.976758
Iteration : 2 | Cost : 9.958066
Iteration : 3 | Cost : 9.939374
Iteration : 4 | Cost : 9.920717
Iteration : 5 | Cost : 9.902031
Iteration : 6 | Cost : 9.883356
Iteration : 7 | Cost : 9.864702
Iteration : 8 | Cost : 9.846000
Iteration : 9 | Cost : 9.827344
Iteration : 10 | Cost : 9.808667
Iteration : 11 | Cost : 9.790002
Iteration : 12 | Cost : 9.771323
Iteration : 13 | Cost : 9.752639
Iteration : 14 | Cost : 9.733966
Iteration : 15 | Cost : 9.715297
Iteration : 16 | Cost : 9.696613
Iteration : 17 | Cost : 9.677936
Iteration : 18 | Cost : 9.659271
Iteration : 19 | Cost : 9.640594
Iteration : 20 | Cost : 9.621925
Iteration : 21 | Cost : 9.603248
Iteration : 22 | Cost : 9.584570
Iteration : 23 | Cost : 9.565892
Iteration : 24 | Cost : 9.547216
Iteration : 25 | Cost : 9.528543
Iteration : 26 | Cost : 9.509864
Iteration : 27 | Cost : 9.491194
Iteration : 28 | Cost : 9.472522
Iteration : 29 | Cost : 9.453843
Iteration : 30 | Cos

In [43]:
# fourbyfour = np.mat('9, 8, 7, 9; 3, 7, 1, 8; 2, 4, 7, 4; 6, 2, 3, 5')
# fourbythree = np.mat('1, 2, 4; 3, 5, 8; 6, 8, 9; 2, 5, 8')
# dot = format(np.dot(fourbyfour, fourbythree))
# mat = format(np.matmul(fourbyfour, fourbythree))

# print("np.dot = \n")
# print(dot)
# print("np.matmul =\n")
# print(mat)

np.dot = 

[[ 93 159 235]
 [ 46  89 141]
 [ 64 100 135]
 [ 40  71 107]]
np.matmul =

[[ 93 159 235]
 [ 46  89 141]
 [ 64 100 135]
 [ 40  71 107]]


In [37]:
# fourbyfour = np.array([
#                        [1,2,3,4],
#                        [3,2,1,4],
#                        [5,4,6,7],
#                        [11,12,13,14]
#                       ])


# twobyfourbythree = np.array([
#                              [[2,3],[11,9],[32,21],[28,17]],
#                              [[2,3],[1,9],[3,21],[28,7]],
#                              [[2,3],[1,9],[3,21],[28,7]],
#                             ])

# print('4x4*4x2x3 dot:\n {}\n'.format(np.dot(fourbyfour,twobyfourbythree)))
# print('4x4*4x2x3 matmul:\n {}\n'.format(np.matmul(fourbyfour,twobyfourbythree)))
# # print(twobyfourbythree)
# # print(fourbyfour)

[[[ 2  3]
  [11  9]
  [32 21]
  [28 17]]

 [[ 2  3]
  [ 1  9]
  [ 3 21]
  [28  7]]

 [[ 2  3]
  [ 1  9]
  [ 3 21]
  [28  7]]]
[[ 1  2  3  4]
 [ 3  2  1  4]
 [ 5  4  6  7]
 [11 12 13 14]]
